networks:
  marketflow-network:

services:
  db:
    image: postgres:latest
    container_name: marketplace-db
    networks:
      - marketflow-network
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq1
    networks:
      - marketflow-network
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace-app
    networks:
      - marketflow-network
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://marketplace-db:5432/marketplace  # ✅ Ajuste para garantir que o nome correto do banco seja usado
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgre
      SPRING_RABBITMQ_HOST: rabbitmq1  # ✅ Ajuste para garantir conexão ao RabbitMQ
      SPRING_RABBITMQ_PORT: 5672
    ports:
      - "8080:8080"
    command: ["sh", "-c", "sleep 15 && java -jar /app/ms-pedido.jar"]
